tasks/config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: [:edit]
  post '/tasks/new', to: 'tasks#new'
  patch '/subtasks/:id/complete', to: 'tasks#complete'
  patch 'subtasks/:id', to: 'tasks#createSubtasks'
  patch 'subtasks/:id/split', to: 'tasks#split', defaults: { format: 'js' }
  patch 'subtasks/:id/completeExtra', to: 'tasks#completeExtra'
  patch 'subtasks/:id/rename', to: 'tasks#rename'

  devise_for :users, controllers:{users: "users", registrations: 'registrations'}
  get 'users/:id', to: 'users#show', as: :user

  root 'tasks#index'
end

tasks/app/models/subtask.rb
class Subtask < ActiveRecord::Base
  belongs_to :task
  acts_as_tree
  accepts_nested_attributes_for :children
  
  def calcLevel
    ancestors.length+1
  end
end

tasks/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :subtasks, dependent: :destroy
  accepts_nested_attributes_for :subtasks
  def get_total_percent
     subtasks.map{|s| s.percent if s.complete}.compact.sum.to_s
  end
end

tasks/app/models/user.rb
class User < ActiveRecord::Base
#   Include default devise modules. Others available are:
#   :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  has_many :tasks, dependent: :destroy
  validates_presence_of :username
  validates_uniqueness_of :username
  validates_presence_of :password, on: :create
  validates_confirmation_of :password, on: :create
  validates_length_of :password, within: Devise.password_length, allow_blank: true

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def avatar_path
    username+"/avatar.jpg"
  end
end

tasks/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

tasks/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, only: [:create, :update]

  def edit
    @cancel=true;
    @back=true;
  end

  def create
    super
    @uploaded_io = params[:user][:avatar]
    Dir.mkdir(user_dir_path, 0700) unless Dir.exist? user_dir_path
    if params[:user][:avatar]
      File.open user_dir_path.join('avatar.jpg'), 'wb' do |file|
        file.write(@uploaded_io.read)
      end
    end
  end

  def update
    super
    @uploaded_io = params[:user][:avatar]
    if params[:user][:avatar]
      File.open user_dir_path.join('avatar.jpg'), 'wb' do |file|
        file.write(@uploaded_io.read)
      end
    end
  end
  
  private
    def user_dir_path
      Rails.root.join('app', 'assets', 'images', params[:user][:username])
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:bio, :avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:bio, :avatar])
    end
end

tasks/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_subtask, only: [:complete, :completeExtra, :createSubtasks, :split, :rename]
  respond_to :js, only: [:complete, :split, :rename]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where user_id: current_user.id
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @subtasks=@task.subtasks.select{|s| s.parent_id==nil}
    @back=true
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @numSubTasks=(params[:number_subtasks]!=nil) ? params[:number_subtasks].to_i : 4
    (1..@numSubTasks).each do |i| @task.subtasks.new complete: false end
    @count=0
    @remainder=100 % @numSubTasks
    @back=true
    @cancel=true
  end

  # GET /tasks/1/edit
  def edit
    @back=true
    @cancel=true
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user=current_user
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def complete
    @subtask.update_attribute :complete, true
    respond_with(@subtask)
  end

  def split
    @back=true
    @cancel=true
    @numSubTasks=(params[:number_subtasks]).to_i
    (1..@numSubTasks).each do |i| @subtask.children.build(name: i.to_s, percent: 100/@numSubTasks) end
    @count=0
    @remainder= 100 % @numSubTasks
    @subtask.save
    respond_with @subtask
  end

  def createSubtasks
    @children=params[:subtask][:children_attributes].to_a.map{|x| x[1]}
    @children.each do |x| @subtask.children.build(name: x["name"], percent: x["percent"], task_id: @subtask.task_id).save end
    redirect_to @subtask.task
  end
 
  def completeExtra
    if params[:el]=="mainProgressBar"
      @subtask.task.update_attribute(:complete, true)
    else
      Subtask.find(@subtask.parent_id).update_attribute(:complete, true)
    end
  end

  def rename
    @subtask.update_attribute :name, params[:subtask][:name]
    head :no_content
  end

  helper_method :get_progress_value
  def get_progress_value task
    if task.is_a? Task
      return task.subtasks.map{|t| get_progress_value t if t.parent_id==nil}.compact.sum
    elsif task.children.empty?
      return (if task.complete then task.percent else 0 end)
    else
      return task.children.map{|t| get_progress_value t}.sum*(task.percent.to_f/100.0) 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_subtask
      @subtask = Subtask.find(params[:id]);
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, subtasks_attributes: [:name, :percent])
    end
end

tasks/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @hideNav=true;
  end
end

tasks/app/helpers/application_helper.rb
module ApplicationHelper
end

tasks/app/helpers/tasks_helper.rb
module TasksHelper
end

tasks/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body <%="class=\"taskView\"".html_safe%>>
<%unless @hideNav || !user_signed_in? %>
  <div id="user_nav">
    Signed in as <%= current_user.username %>.   
    <div class="alignright">
      <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
    </div>
    <div class="alignright">
      <%= button_to "View Profile", current_user, method: :get %> <br>
    </div>   
    <div class="alignright">
      <%= button_to (@cancel ? 'Cancel' : 'Back'), tasks_path, method: :get if @back %>
    </div>
  </div>
<%end%>

<%= yield %>

</body>
</html>

tasks/app/views/subtasks/_subtask.html.erb
<div id="subtask<%=subtask.id%>"> 
  <div id="split<%=subtask.id%>" style="display:inline; width:99%">
    <div class="subTaskName" id="name<%=subtask.id%>">
      <%=subtask.name%>
    </div>
    <div class="subTaskRename" id="rename<%=subtask.id%>">
      <%=form_for subtask, url: {action: "rename", id: subtask.id}, remote: true do |f|%>
        <%=f.text_field :name%>
        <%=f.submit "Save Name"%>
      <%end%>
    </div>
    <%if subtask.children.empty?%>
      <%unless subtask.complete%>
        <div class="alignright">
          <%=render "split", subtask: subtask%>
        </div>
        <div class="alignright">
          <%=render "complete", subtask: subtask%>
        </div>
      <%else%>
        <div class="alignright">
          <%=image_tag "/assets/complete.png", size:"16x16"%>
        </div>
      <%end%>
    <%else%>
      <%unless subtask.complete%>
        <div class="alignright">
          <progress id="progressBar<%=subtask.id%>" value=<%=(get_progress_value subtask)*100/subtask.percent.to_f%> max="100" style="height:15px;"></progress>
        </div>
      <%else%>
        <div class="alignright"> 
          <%=image_tag "/assets/complete.png", size:"16x16"%>
        </div>
      <%end%>
    <%end%>
    <div class="alignright">
      <input type="button" value="Rename" id='rbutton<%=subtask.id%>'> 
    </div>
  </div>

  <div style="clear: both;"></div>

  <%if !subtask.children.empty? %>
    <%if !subtask.parent_id %>
      <hr class=two>
    <%else%>
      <hr class=three>
    <%end%>
  <%else%>
    <br>
  <%end%>
  <div style="padding-left:30px">
    <%=render subtask.children%>
  </div>
</div>

<script> SetUpRNHandler(<%=subtask.id%>); </script>

tasks/app/views/tasks/_complete.html.erb
<%= form_for(subtask, url: {controller: "tasks", action: "complete", id: subtask.id.to_s}, remote: true) do |f| %>
  <%=f.submit "Complete", onsubmit: "complete(#{subtask.id});"%>
<% end %>

tasks/app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%if@task.new_record?%>
    <h3>Subtasks</h3>
    <%= f.fields_for :subtasks do |subtasks_form| %>
      <div style="margin-left:30px;">
        <div class="field">
          <%= subtasks_form.label :name %><br>
          <%= subtasks_form.text_field :name %>
        </div>
          <div class="field">
            <%= subtasks_form.hidden_field :percent, value: 100/@numSubTasks.to_f %>
          </div>
          <%@count+=1%>
      </div>
    <% end %><br>
  <%end%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tasks/app/views/tasks/_renameButton.html.erb
<%= form_for(subtask, url: {controller: "tasks", action: "rename", id: subtask.id.to_s}, remote: true) do |f| %>
  <%=f.submit "Rename"%>
<% end %>

tasks/app/views/tasks/_split.html.erb
<%=form_for(subtask, url: {controller: "tasks", action: "split", id: subtask.id.to_s}, remote: true) do |f|%>
  <%=f.submit("Split")%>
  <%=select_tag(:number_subtasks, options_for_select(2..10)) %>
<% end -%>

tasks/app/views/tasks/complete.js.erb
function move(el, amt){
  var width = el.prop('value');
  var end = width+Number(amt);
  var id = setInterval(frame, 10);
  function frame(){
    if (width >= end) {
      clearInterval(id);
      if(end>=99){
        el.prop('value', '100');
        if(el.attr('id')!='mainProgressBar'){
          el.before("<img src='<%= asset_path('assets/complete.png')%>', width='16', height='16' />");
        }
        $.ajax({
          type: "PATCH",
          url:'/subtasks/<%=@subtask.id.to_s%>/completeExtra',
          data:(
            'id=' + <%=@subtask.id.to_s%>,
            'el=' + el.attr('id')
          )
        })
      }
    } else {
      width+=.75;
      el.prop('value', width);
    }
  }
}

$('#split'+<%=@subtask.id%>).replaceWith("<img src='<%= asset_path('assets/complete.png')%>', width='16', height='16' />");
var percent=<%=@subtask.percent%>;
<%while @subtask.calcLevel>1 do%>
  <%@subtask=Subtask.find(@subtask.parent_id)%>
  move($('#progressBar'+<%=@subtask.id%>), percent);
  percent=percent*<%=@subtask.percent%>/100;
<% end %>

move($('#mainProgressBar'), percent);

tasks/app/views/tasks/index.html.erb
<h1>Your Tasks</h1>
<%if @tasks.length>0%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Progress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.name, task %> <%= image_tag "/assets/complete.png", size: "16x16" if task.complete%></td>
        <td style="width:70%; padding-left:1em;"><progress value=<%=get_progress_value task%> max="100" style="width:100%; height:15px;"></progress></td>
        <td style="padding-left:1em;"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>

<br>
<%= form_tag new_task_path :method => :post do %>
  Select number of subtasks:
  <%= select_tag(:number_subtasks, options_for_select(1..10))%>
  <%= submit_tag 'New Task' %>
<% end %>

tasks/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

tasks/app/views/tasks/rename.js.erb
var id = <%=@subtask.id%>;
var el = $('#name'+id)[0];

var val = el.innerHTML;
var input = document.createElement("input");
input.type = "text";
input.value = val.trim();
el.style.display = "none";
el.parentNode.insertBefore(input, el);

var sub = document.createElement("submit");
sub.value = 'Submit';
el.parentNode.insertBefore(sub, el);

var canc = document.createElement("submit");
canc.value = 'Cancel';
el.parentNode.insertBefore(canc, el);

$('#sub'+id).click(function(){
  $.ajax();
});

tasks/app/views/tasks/show.html.erb
<h1 style="text-align:center;"><%=@task.name%></h1> 

<progress id="mainProgressBar" value=<%=get_progress_value @task%>  max="100" style="width:100%; height:30px;"></progress>
<br>
<hr class=one>
<div class="subTaskBox">
  <div class="subTaskWrap">
    <div class="subTasks">
      <%=render @subtasks%>
    </div>
  </div>
</div>

tasks/app/views/tasks/split.html.erb
<h3>Split Subtask "<%=@subtask.name%>"</h3>
<%=form_for @subtask do |f| %>
  <% if @subtask.errors.any? %>
    <div id="error_explanation">
      <h2><%=pluralize @task.errors.count, "error" %> prohibited this task from being saved:</h2>
      <ul>
      <% @subtask.errors.full_messages.each do |message| %>
        <li><%= message %> </li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%@subtask.children.each do |sub|%>
    <%=f.fields_for :children, sub do |form| %>
      <div class="field">
        <%=form.label :name %><br>
        <%=form.text_field :name%>
      </div>
      <div class="field">
        <%=form.hidden_field :percent, value: 100/@numSubTasks.to_f %>
      </div>
      <%@count+=1%>
    <% end %>
  <%end%><br>
  <div class="actions">
    <%=f.submit %>
  </div>
<% end %>

tasks/app/views/tasks/split.js.erb
$("<%='#subtask'+@subtask.id.to_s%>")[0].innerHTML = '<%= j render @subtask %>';

tasks/app/views/users/show.html.erb
<!DOCTYPE HTML>
<h1><%=current_user.username%>'s profile.</h1>
<%if current_user.avatar%>
  <%= image_tag current_user.avatar_path, size: "250x250" %>
<%else%>
  <%= image_tag "/assets/noavatar.png", size: "250x250" %>
<%end%>
<br>
<h3>About <%=current_user.username%></h3>
<hr class=two>
<%= current_user.bio %>
<br>
<%= button_to "Edit Profile", edit_user_registration_path(current_user), method: :get %>
<%= button_to "Back", tasks_path, method: :get %>